title: My first Github Page Journey
author: Xiaoyi
email: xiaoyitravel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My first Github page.

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
